object LibsVersions {
    const val appcompat = "1.6.1"
    const val converter_gson = "2.9.0"
    const val hilt_android_compiler = "2.44"
    const val hilt_compiler = "1.0.0"
    const val ktx = "1.10.1"
    const val lifecycle_runtime_ktx = "2.6.1"
    const val ok_http = "4.10.0"
    const val material = "1.9.0"
    const val constraint = "2.1.4"
    const val navigation = "2.5.3"
    const val coil = "2.4.0"
    const val circle_indicator = "2.1.6"
    const val whynotimagecarousel = "2.1.0"
}